id: P005422
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3170
  title: འདས་ལོག་དཀར་ཆག་ཐར་པའི་ལམ་སྟོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    44b47dc51c6b429fadeac24e39b7e31f:
      image_group_id: I1KG3205
      title: ''
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
