id: IFB24CC02
legacy_id: P005422
ocr_import_info:
  bdrc_scan_id: W1KG3170
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T08:41:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:55:59.598911+00:00'
last_modified: 2022-08-31 22:56:08.608818
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3170
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3170
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདས་ལོག་དཀར་ཆག་ཐར་པའི་ལམ་སྟོན་གསལ་བའི་སྒྲོན་མེ།
  author: སྟག་བླ་དཀོན་མཆོག་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.7612487785657334
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1KG3205:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3205
      total_pages: 316
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3205.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7612487785657334
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
